[project]
name = "proof-of-concept-folium"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.19.5",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
